### ISSUE TITLE
Data location differs per-user if side-loaded using the play.date account website

### ISSUE THREAD

**Issue by gingerbeardman** [mierau/gamekid#1]
In the readme it recommends side-loading through a play.date account.

But in this scenario the data folder will no longer follow the bundleID `app.gamekid.data`; it will instead be something else with only the final part of the reverse dns notation being used. After user the account website to side-load onto my device the Gamekid data folder is called `user.124.data`. 😬

This is, of course, confusing and I struggled with the documentation for [Audition](https://gingerbeardman.itch.io/audition) for this very reason. I ended up referring to it in my documentation as `Data/*.audition` but this is still far from ideal.

**Comment by mierau** [comment]
Thanks! I've updated the README and changed the bundleID. Unfortuneately those who have Gamekid working will need to move their ROMs to the new Gamekid data folder.
