### ISSUE TITLE
Incompatible version (Playdate OS possibily newer)

### ISSUE THREAD

**Issue by dhow** [mierau/gamekid#11]
When I launched the emulator on my Playdate OS 2.0.0 [this error message](https://help.play.date/e4/) appeared.

**Comment by peter-toft** [comment]
hey @dhow have a look at the guide I posted, I have it working on OS 2.0

**Comment by dhow** [comment]
Thanks for letting me know @peter-toft , I left a comment in https://github.com/mierau/gamekid/issues/13 !

**Comment by mierau** [comment]
The latest release should now run under 2.0. Thanks!
https://github.com/mierau/gamekid/releases/tag/v0.5.5
