### ISSUE TITLE
[GUIDE] How to use on OS 2.0

### ISSUE THREAD

**Issue by peter-toft** [mierau/gamekid#13]
I've opened a PR for this change, but I don't know if this package is still maintained so it may not get looked at.

Here are instructions for those who want to edit the file themselves and build the package for use on Playdate OS 2.0 - its just one file.

1. Clone the repo.
2. Open /extensions/libraryview.c
3. On line 125, add an extra argument with the value 1 to the listfiles function. For reference:

> Original line 125:
> `playdate->file->listfiles("/games", listFilesCallback, view);`
> Updated line 125:
> `playdate->file->listfiles("/games", listFilesCallback, view, 1);`

4. Build the project (either run make in the root directory, or use Nova's Build tool if you are a Nova user)
5. Reboot the Playdate into Data Disk mode and add the .pdx file that is now in the root directory of the repo to Games/User (**Sideloading via the Web will not work** unless you also modify the pdxinfo file and increment the build number - Panic appears to use a cached version on their server if the pdx you upload matches an existing build number. I haven't done this out of respect to the original dev)

I am on an M1 Mac so didn't have issues, but I understand that it may not build on Intel Macs or Windows machines. If you have issues and my PR to fix the package hasn't been merged yet, there is also a built .pdx in my fork here - https://github.com/peter-toft/gamekid

**Comment by dhow** [comment]
Hey @peter-toft -- thanks for the sharing, can't believe one argument in source code is blocking it to work on newer OS. I don't have the build environment, would you be able to send me an updated .pdx file?

**Comment by peter-toft** [comment]
@dhow I've added the built pdx to my fork, you can pull it down there - https://github.com/peter-toft/gamekid

**Comment by stuffbyjk** [comment]
Hi Peter,

I can't thank you enough for fixing the compatibility issue with Gamekid!

I'm unfamiliar with how to compile the PDX files. Would you be able to assist me with this process?

I've installed that Playdate SDK and downloaded the Gamekid Master zip. I see a "make" file, but don't know how to run it (windows doesn't recognize which program to use, and the Playdate SDK doesn't seem to be an executable in Program Files.).

Thanks!

**Comment by peter-toft** [comment]
@stuffbyjk just download my modified repo here https://github.com/peter-toft/gamekid. There is directory in it called gamekid.pdx (pdx files are actually just a directory). Use that to follow step 5 of the guide and you are good to go

**Comment by peter-toft** [comment]
@stuffbyjk I don't think you would be able to build it in your windows environment anyway - the libraries used by the original dev have been compiled for ARM processors

**Comment by peter-toft** [comment]
@stuffbyjk I haven't done development on Windows in about 10 years, sorry I can't be more help with getting your own environment working. I think you could use a package manager like chocolatey to install make, or maybe use something like CMake with visual studio.

**Comment by stuffbyjk** [comment]
Hey Peter, thanks for the reply!

To be clear, I'm really just looking for a "compiled" PDX so I can get this onto my playdate -- I'm not interested in playing this on the simulated environment in Windows.

I went through the process of using Visual Studio and Cmake yesterday, but as you indicated, there aren't sufficient files needed to compile on Windows ☹️ 

Is there any chance you can provide a PDX that I can sideload via the Playdate site? It would be nice if your update for firmware 2.0 would be adopted by the original Gamekid developer.

**Comment by peter-toft** [comment]
@stuffbyjk im not sure how to get it to work via the Playdate site, I think it looks at the version number and serves a cached version if a match is found. I could try incrementing it but you don't need that anyway and I'm not sure what effects that could have.

As I said in my earlier comment, there is a built PDX you can side load in my repo here - https://github.com/peter-toft/gamekid. Specifically - https://github.com/peter-toft/gamekid/tree/master/gamekid.pdx

Treat the gamekid.pdx directory as if it is a file. Plug your playdate into your computer in Data Disk mode (its in the System menu on the Playdate). Open the drive in your file explorer, navigate to Games/User, and then drop the .pdx directory in there. Then you should be good to go.

As for the original dev updating the main repo, I've opened a PR but he mustn't be monitoring this anymore. I know he's on Twitter but I don't use it. To be honest, depending on my time in the near future I may just fork this project permanently and develop it further separately to fix other bugs and add some features (I think Select and Start would be good to add to the Playdate side menu, not just the crank for instance).

**Comment by stuffbyjk** [comment]
Hey Peter!

Thanks for clarifying on the pdx folder! I thought the games/software needed to be packaged as a .pdx in order to sideload, regardless of method.

I think I'm running into a compounding issue with my Playdate -- all of my folders in Disk Mode are set to read-only, and I can't get them to unlock. It feels like the same issue you can have with a corrupted SD card. I'm wondering if there's an issue with the solid state storage on my particular Playdate. See here:

https://github.com/risolvipro/PlayGB/issues/6#issuecomment-1641091415

I'd be curious to see if you can compile a .pdx file with the version number iterated-forward, and see if I can use the Playdate website to sideload. I was able to successfully load the "latest" Gamekid version no problem using this method, but it's of course incompatible :)

**Comment by peter-toft** [comment]
@stuffbyjk ok I’ll build you an incremented file - it’ll be a few hours until im able get to it, I’ll leave you a note here when I do

**Comment by mierau** [comment]
Sorry I've been busy. I'll take a look at this thread soon and whatever outstanding PRs there are. Thanks so much for contributing!

**Comment by peter-toft** [comment]
@stuffbyjk mierau is going to bring it in to the main repo so I'll leave it there. I assume he'll probably do a release of a new built pdx with an updated version after this happens. @mierau I've opened a cleaned up new PR with the required change, should be good to go.

**Comment by mierau** [comment]
Alright, thanks again! Sorry I've been so busy with other projects. I will try to keep an eye out for PRs here and hope to make some time to work on performance soon.

The latest release should work under 2.0: https://github.com/mierau/gamekid/releases/tag/v0.5.5

**Comment by stuffbyjk** [comment]
Thanks so much for the quick turnaround, guys!

I'll try uploading the game via the wifi sideload tool on Play.date and let you know how I fare.
